name: Linting
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: goLint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run:  sudo apt update && sudo apt-get -y install gcc tar wget libgtk-3-dev libappindicator3-dev libxapp-dev libwebkit2gtk-4.0-dev build-essential
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Install Go dependencies for icon generation
        run: go get -u github.com/cratonica/2goarray
      - name: Generate tray-agent icons
        run: |
          chmod +x ./scripts/make_icon.sh
          ./scripts/make_icon.sh
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29.0
          args: --timeout=600s -D unused,structcheck -E prealloc,gofmt,govet --skip-files "zz_generated.*.go"
  shelllint:
    name: shellLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
